
postTitleAfter: boldLine   # 文章标题后的装饰样式 (可选值：boldLine/underline等)
colorScheme: pink          # 网站整体配色方案 (可选值：pink/blue/dark等)
cdn: local               # 静态资源CDN服务商 (可选：bootcdn/jsdelivr/unpkg)
favicon: /images/avatar.ico # 浏览器标签页显示的网站图标
enablepjax: true           # 是否启用无刷新页面加载技术



code_block:
  line_numbers: true       # 是否显示代码行号
  copy_button: true        # 是否显示复制代码按钮
  pjax_script:             # PJAX重载时的回调脚本 (可选)
    # 示例：
    #   pjax_script: 'console.log("PJAX reloaded")'


# 左侧导航栏标识设置
logoIndex: /images/avatar.ico   # 导航栏LOGO图片路径
logoIndexUrl:                   # LOGO点击跳转链接 (留空则不跳转)

# 作者信息展示
authorAvatar: /images/avatar.ico  # 作者头像路径

# 左侧导航栏文字内容
titleIndex: 你好，世界          # 导航栏主标题文字
descriptionIndex: 一个前端开发工程师  # 导航栏副标题描述



leftSideCustomCode: 
  # 示例（可插入HTML/JS代码）：
  #   - <div class="custom-banner">Hello World</div>
  #   - <script>console.log('Custom code loaded')</script>


# 导航菜单配置
menu:
  - name: home      # 菜单项显示名称
    url: /          # 菜单项链接地址
  - name: about
    url: /about/


# 侧边栏配置
showSearch: true          # 是否显示搜索框
showCategory: true        # 是否显示文章分类
showTag: true             # 是否显示标签云


showTOC: true             # 是否显示文章目录
showWordCount: true       # 是否显示字数统计
showCopyright: true       # 是否显示版权声明


comment:
  enable: true
  type: twikoo # 评论系统类型
  app:
    twikoo:
      envId: '您的环境id' ## 腾讯云环境填 envId；Vercel 环境填地址（https://xxx.vercel.app）
      region: 'ap-guangzhou' ## 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填
      path: location.pathname ## 用于区分不同文章的自定义 js 路径，如果您的文章路径不是 location.pathname，需传此参数
      lang: 'zh-CN' ## 用于手动设定评论区语言，支持的语言列表 https://github.com/twikoojs/twikoo/blob/main/src/client/utils/i18n/index.js

# 页脚配置
footerInfo: 2023 © 你好，世界  # 页脚显示的文字/HTML内容

