postTitleAfter: boldLine
colorScheme: pink
cdn: bootcdn
favicon: /images/avatar.ico


code_block:
  line_numbers: true     # 启用行号
  copy_button: true      # 启用复制按钮
  pjax_script:          # 可选的PJAX脚本


# 左侧 LOGO 地址
logoIndex: /images/avatar.ico
logoIndexUrl: # LOGO 跳转 地址

authorAvatar: /images/avatar.ico

# 网站左侧标题文字
titleIndex: 你好，世界

# 左侧个人描述
descriptionIndex: 一个前端开发工程师


# 左侧左侧自定义区域
leftSideCustomCode:


menu:
  - name: home
    url: /
  - name: about
    url: /about/

showSearch: 
showCategory: true
showTag: true
showTOC: true

hasImg